{% set version = "25.1.0" %}

package:
  name: mesalib-split
  version: {{ version }}

source:
  url: https://archive.mesa3d.org/mesa-{{ version }}.tar.xz
  sha256: b1c45888969ee5df997e2542654f735ab1b772924b442f3016d2293414c99c14

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - meson >=0.63.0
    - ninja
    - pyyaml
    - mako
    - packaging
    - python 3.12  # [linux]
    - python 3.11  # [osx]
    - flex
    - bison
    - pkg-config
    - llvm
    - llvmdev  # [build_platform != target_platform]
    - glslang
    - git  # [linux]
  host:
    - expat 2.5.0
    - zlib {{ zlib }}
    - zstd {{ zstd }}
    - libdrm  # [linux]
    - spirv-tools 2025.1
    - llvm 17.0.6
    - llvmdev 17.0.6
    - libxcb  # [linux]
    - xorg-libx11  # [linux]
    - xorg-xorgproto  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxshmfence  # [linux]
    - xorg-libxfixes 6.0.1  # [linux]
    - xorg-libxdamage  # [linux]
    - xorg-libxxf86vm  # [linux]
    - libgl-devel  # [linux]
    - libglvnd  # [linux]
    - libglvnd-devel  # [linux]
    - libunwind 1.5.0  # [linux]

outputs:
  # Mesa GBM implementation (only on Linux)
  - name: mesa-libgbm
    build:
      run_exports:
        - {{ pin_subpackage('mesa-libgbm', max_pin='x.x') }}
      ignore_run_exports:
        - libstdcxx-ng
      skip: true  # [osx]
    files:
      - lib/libgbm.so*
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - libdrm  # [linux]
        - expat
      run:
        - libdrm  # [linux]
        - expat
    test:
      commands:
        - test -f $PREFIX/lib/libgbm${SHLIB_EXT}  # [linux]

  # Base package with core Mesa components
  - name: mesalib
    build:
      run_exports:
        - {{ pin_subpackage('mesalib', max_pin='x.x') }}
        - {{ pin_subpackage('mesa-dri-drivers', max_pin='x.x') }}  # [linux]
      ignore_run_exports:
        - libstdcxx-ng
        - xorg-libx11
        - xorg-libxext
        - llvm
        - llvmdev
    files:
      - lib/dri/*.so*  # [linux]
      - lib/libgallium*.so*  # [linux]
      - lib/libgallium*.dylib*  # [osx]
      - include/**
      - share/drirc.d/**
      - share/glvnd/**  # [linux]
      - share/mesa/**
      - bin/mesa*  # [linux]
      # Exclude gbm.h since it belongs to mesa-libgbm-devel
      # Other headers will be moved to their respective devel packages
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('mesa-libgbm', exact=True) }}  # [linux] # Needed at build time for linking
        - libdrm  # [linux]
        - xorg-libx11 >=1.8.12,<2.0a0  # [linux]
        - xorg-libxext >=1.3.6,<2.0a0  # [linux]
        - xorg-libxdamage  # [linux]
        - xorg-libxxf86vm  # [linux]
        - expat
        - libxcb  # [linux]
        - llvm 17.0.6
        - llvmdev 17.0.6
        - zlib
        - zstd
        - spirv-tools 2025.1
        - xorg-libxshmfence  # [linux]
        - libstdcxx-ng  # [linux]
      run:
        - {{ pin_subpackage('mesa-libgbm', exact=True) }}  # [linux] # DRI drivers need libgbm.so
        - libdrm  # [linux]
        - xorg-libx11 >=1.8.12,<2.0a0  # [linux]
        - xorg-libxext >=1.3.6,<2.0a0  # [linux]
        - xorg-libxdamage  # [linux]
        - xorg-libxxf86vm  # [linux]
        - expat
        - libxcb  # [linux]
        - llvm 17.0.6
        - llvmdev 17.0.6
        - zlib
        - zstd
        - spirv-tools 2025.1
        - xorg-libxshmfence  # [linux]
        - libstdcxx-ng  # [linux]
    test:
      commands:
        - test -f $PREFIX/lib/dri/softpipe_dri${SHLIB_EXT}  # [linux]
        - test -f $PREFIX/lib/dri/kms_swrast_dri${SHLIB_EXT}  # [linux]
        # Check that at least one of GLES2 or GL directories exists
        - test -d $PREFIX/include/GLES2 || test -d $PREFIX/include/GL  # [unix]

  # Mesa DRI drivers package (only on Linux)
  - name: mesa-dri-drivers
    build:
      ignore_run_exports:
        - libstdcxx-ng
      skip: true  # [osx]
    files:
      - lib/dri/*.so*
    requirements:
      host:
        - {{ pin_subpackage('mesalib', exact=True) }}
        - libdrm  # [linux]
        - expat
      run:
        - {{ pin_subpackage('mesalib', exact=True) }}
        - libdrm  # [linux]
        - expat
    test:
      commands:
        - test -f $PREFIX/lib/dri/softpipe_dri${SHLIB_EXT}  # [linux]
        - test -f $PREFIX/lib/dri/kms_swrast_dri${SHLIB_EXT}  # [linux]

  # Mesa GL implementation (only on Linux)
  - name: mesa-libgl
    build:
      run_exports:
        - {{ pin_subpackage('mesa-libgl', max_pin='x.x') }}
      ignore_run_exports:
        - libstdcxx-ng
        - libglvnd
        - llvm
        - llvmdev
      skip: true  # [osx]
    files:
      - lib/libGLX_mesa.so*
      - lib/libGL.so*
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('mesalib', exact=True) }}
        - libglvnd  # [linux]
        - expat
        - xorg-libx11 >=1.8.12,<2.0a0  # [linux]
        - libxcb  # [linux]
        - libdrm  # [linux]
        - llvmdev 17.0.6
      run:
        - {{ pin_subpackage('mesalib', exact=True) }}
        - libglvnd  # [linux]
        - expat
        - xorg-libx11 >=1.8.12,<2.0a0  # [linux]
        - libxcb  # [linux]
        - libdrm  # [linux]
        - llvmdev 17.0.6
    test:
      commands:
        - test -f $PREFIX/lib/libGLX_mesa${SHLIB_EXT}  # [linux]

  # Mesa GL development files (only on Linux)
  - name: mesa-libgl-devel
    build:
      run_exports:
        - {{ pin_subpackage('mesa-libgl', max_pin='x.x') }}
      skip: true  # [osx]
    files:
      - lib/pkgconfig/gl.pc
      - include/GL/*.h
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('mesa-libgl', exact=True) }}
        - libgl-devel  # [linux]
      run:
        - {{ pin_subpackage('mesa-libgl', exact=True) }}
        - libgl-devel  # [linux]
    test:
      requires:
        - pkg-config
      commands:
        - pkg-config --exists gl  # [linux]

  # Mesa EGL implementation (only on Linux)
  - name: mesa-libegl
    build:
      run_exports:
        - {{ pin_subpackage('mesa-libegl', max_pin='x.x') }}
      ignore_run_exports:
        - libstdcxx-ng
        - libglvnd
        - mesalib
    - llvm
    - llvmdev
      skip: true  # [osx]
    files:
      - lib/libEGL_mesa.so*
      - lib/libEGL.so*
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('mesalib', exact=True) }}
        - {{ pin_subpackage('mesa-libgbm', exact=True) }}
        - libglvnd  # [linux]
        - libdrm  # [linux]
        - expat
        - xorg-libx11 >=1.8.12,<2.0a0  # [linux]
        - libxcb  # [linux]
        - llvmdev 17.0.6
      run:
        - {{ pin_subpackage('mesalib', exact=True) }}
        - {{ pin_subpackage('mesa-libgbm', exact=True) }}
        - libglvnd  # [linux]
        - libdrm  # [linux]
        - expat
        - xorg-libx11 >=1.8.12,<2.0a0  # [linux]
        - libxcb  # [linux]
        - llvmdev 17.0.6
    test:
      commands:
        - test -f $PREFIX/lib/libEGL_mesa${SHLIB_EXT}  # [linux]

  # Mesa EGL development files (only on Linux)
  - name: mesa-libegl-devel
    build:
      run_exports:
        - {{ pin_subpackage('mesa-libegl', max_pin='x.x') }}
      skip: true  # [osx]
    files:
      - lib/pkgconfig/egl.pc
      - include/EGL/*.h
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('mesa-libegl', exact=True) }}
        - libegl-devel  # [linux]
      run:
        - {{ pin_subpackage('mesa-libegl', exact=True) }}
        - libegl-devel  # [linux]
    test:
      requires:
        - pkg-config
      commands:
        - pkg-config --exists egl  # [linux]

  # Mesa GBM development files (only on Linux)
  - name: mesa-libgbm-devel
    build:
      run_exports:
        - {{ pin_subpackage('mesa-libgbm', max_pin='x.x') }}
      skip: true  # [osx]
    files:
      - lib/pkgconfig/gbm.pc
      - include/gbm.h
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('mesa-libgbm', exact=True) }}
      run:
        - {{ pin_subpackage('mesa-libgbm', exact=True) }}
test:
  requires:
    - pkg-config
  commands:
        - pkg-config --exists gbm  # [linux]

  # Mesa OSMesa implementation (supported on both Linux and macOS)
  # Note: In Mesa 25.1.0, OSMesa functionality might be integrated differently, but we keep the package for compatibility
  - name: mesa-osmesa
    build:
      run_exports:
        - {{ pin_subpackage('mesa-osmesa', max_pin='x.x') }}
    files:
      - lib/libOSMesa.so*  # [linux]
      - lib/libOSMesa.dylib*  # [osx]
    requirements:
      host:
        - {{ pin_subpackage('mesalib', exact=True) }}
        - llvmdev 17.0.6
        - spirv-tools 2025.1
      run:
        - {{ pin_subpackage('mesalib', exact=True) }}
        - llvmdev 17.0.6
        - spirv-tools 2025.1
    test:
      commands:
        # Check for OSMesa library if it exists
        - if [ -f $PREFIX/lib/libOSMesa${SHLIB_EXT} ]; then echo "OSMesa found"; else echo "OSMesa not found, but that's OK in Mesa 25.1.0"; fi

  # Mesa Vulkan drivers (supported on both Linux and macOS)
  - name: mesa-vulkan-drivers
    build:
      ignore_run_exports:
        - libstdcxx-ng
        - llvm
        - llvmdev
        - mesalib
    files:
      - lib/libvulkan_*.so*  # [linux]
      - lib/libvulkan_*.dylib*  # [osx]
      - share/vulkan/**
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - glslang
      host:
        - {{ pin_subpackage('mesalib', exact=True) }}
        - expat
        - libdrm  # [linux]
        - xorg-libx11 >=1.8.12,<2.0a0  # [linux]
        - libxcb  # [linux]
        - spirv-tools 2025.1
        - llvmdev 17.0.6
        - libllvm17 17.0.6
        - zlib
        - zstd
        - xorg-libxshmfence  # [linux]
        - libstdcxx-ng  # [linux]
      run:
        - {{ pin_subpackage('mesalib', exact=True) }}
        - expat
        - libdrm  # [linux]
        - xorg-libx11 >=1.8.12,<2.0a0  # [linux]
        - libxcb  # [linux]
        - spirv-tools 2025.1
        - llvmdev 17.0.6
        - libllvm17 17.0.6
        - zlib
        - zstd
        - xorg-libxshmfence  # [linux]
        - libstdcxx-ng  # [linux]
    test:
      commands:
        # Linux specific tests
        - test -f $PREFIX/lib/libvulkan_swrast.so  # [linux]
        - test -f $PREFIX/lib/libvulkan_virtio.so  # [linux]
        # macOS specific tests
        - test -f $PREFIX/share/vulkan/icd.d/lvp_icd.aarch64.json || test -f $PREFIX/share/vulkan/icd.d/lvp_icd.x86_64.json || test -f $PREFIX/share/vulkan/icd.d/swrast_icd.aarch64.json || test -f $PREFIX/share/vulkan/icd.d/swrast_icd.x86_64.json  # [osx]
        # Common tests for all platforms
        - test -n "$(ls -A $PREFIX/share/vulkan/icd.d/*.json 2>/dev/null)"  # [unix]

about:
  home: https://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: docs/license.rst
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.
  description: |
    Mesa is a collection of graphics libraries and drivers that implement a variety of APIs such as OpenGL, Vulkan, and others. It provides software rendering and hardware acceleration for 3D graphics.
  dev_url: https://gitlab.freedesktop.org/mesa/mesa
  doc_url: https://docs.mesa3d.org/

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - sankhesh
    - danlipsa
    - hmaarrfk
    - downiec
    - jasonb5
    - matthiasdiener