{% set version = "25.1.0" %}

package:
  name: mesalib
  version: {{ version }}

source:
  url: https://archive.mesa3d.org/mesa-{{ version }}.tar.xz
  sha256: b1c45888969ee5df997e2542654f735ab1b772924b442f3016d2293414c99c14

build:
  skip: true  # [win]
  number: 0
  track_features:
    - mesalib
  run_exports:
    - {{ pin_subpackage('mesalib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # Some optional Rust-based components (like the Rust video codec implementations) are being enabled in build.sh:
    # -Dgallium-drivers=all implicitly includes Rust-based drivers.
    - {{ compiler('rust') }}
    - meson
    - pyyaml
    - mako
    # packaging is used to check versions at build time
    - packaging
    # conda_build.exceptions.CondaBuildException: Empty package; python dep present in build but not host requirements.
    - python 3.12  # [linux]
    - flex
    - bison
    - pkg-config
    - llvm
    - llvmdev  # [build_platform != target_platform]
    - glslang
    # Git program not found, cannot download DirectX-Headers.wrap via git.
    - git  # [linux]
  host:
    - expat 2.5.0
    - zlib  {{ zlib }}
    - zstd  {{ zstd }}
    - libdrm  # [linux]
    - spirv-tools 2025.1
    - llvm 17.0.6
    - llvmdev 17.0.6
    - libxcb
    - xorg-libx11
    - xorg-xorgproto
    - xorg-libxrandr
    - xorg-libxshmfence
    # libglvnd-devel is needed for libglvnd.pc, otherwise the build fails
    - libglvnd-devel  # [linux]
    # -Dlibunwind=enabled
    - libunwind 4.0.1

test:
  requires:
    - pkg-config
  commands:
    # We assert that we didn't build screen rendering capabilities.
    # We want on-screen rendering capabilities to be hardware accelerated
    # but that will take more effort
    - test ! -f $PREFIX/lib/dri/kms_swrast_dri${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/dri/swrast_dri${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/libgbm${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/libGLESv1_CM${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/libGLESv2${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/libEGL${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/libGL${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libvulkan_*${SHLIB_EXT}  # [unix]
    - test -n "$(ls -A $PREFIX/share/vulkan/icd.d/*.json 2>/dev/null)"  # [x86_64]
    - test -n "$(ls -A $PREFIX/share/vulkan/icd.d/*.json 2>/dev/null)"  # [aarch64]
    - test ! -f $PREFIX/lib/libGLESv1_CM.1${SHLIB_EXT}  # [osx]
    - test ! -f $PREFIX/lib/libGLESv2.2${SHLIB_EXT}  # [osx]
    - test -f $PREFIX/lib/libOSMesa.8${SHLIB_EXT}  # [osx]
    - test ! -f $PREFIX/lib/libGL.1${SHLIB_EXT}  # [osx]
    # - pkg-config --exists glesv1_cm
    # - pkg-config --exists glesv2
    # - pkg-config --exists gl
    # - pkg-config --exists egl
    # - pkg-config --exists gbm       # [linux]

about:
  home: https://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: docs/license.rst
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.
  description: |
    Mesa is a collection of graphics libraries and drivers that implement a variety of APIs such as OpenGL, Vulkan, and others. It provides software rendering and hardware acceleration for 3D graphics.
  dev_url: https://gitlab.freedesktop.org/mesa/mesa
  doc_url: https://docs.mesa3d.org/

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - sankhesh
    - danlipsa
    - hmaarrfk
    - downiec
    - jasonb5
    - matthiasdiener