{% set version = "25.1.0" %}

package:
  name: mesalib
  version: {{ version }}

source:
  url: https://archive.mesa3d.org/mesa-{{ version }}.tar.xz
  sha256: b1c45888969ee5df997e2542654f735ab1b772924b442f3016d2293414c99c14

build:
  number: 0
  skip: true  # [win]
  track_features:
    - mesalib
  run_exports:
    - {{ pin_subpackage('mesalib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - meson >=0.63.0
    - ninja
    - pyyaml
    - mako
    - packaging
    - python 3.12
    - flex
    - bison
    - pkg-config
    - llvm
    - llvmdev  # [build_platform != target_platform]
    - glslang
    - git  # [linux]
  host:
    - expat 2.5.0
    - zlib
    - zstd
    - libdrm  # [linux]
    - spirv-tools 2025.1
    - llvm 17.0.6
    - llvmdev 17.0.6
    - libxcb  # [linux]
    - xorg-libx11  # [linux]
    - xorg-xorgproto  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxshmfence  # [linux]
    - xorg-libxfixes 6.0.1  # [linux]
    - xorg-libxdamage  # [linux]
    - xorg-libxxf86vm  # [linux]
    - libgl-devel  # [linux]
    - libglvnd  # [linux]
    - libglvnd-devel  # [linux]
    - libunwind 1.5.0  # [linux]
  run:
    - expat 2.5.0
    - zlib
    - zstd
    - libdrm  # [linux]
    - spirv-tools 2025.1
    - llvm 17.0.6
    - llvmdev 17.0.6
    - libxcb  # [linux]
    - xorg-libx11  # [linux]
    - xorg-xorgproto  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxshmfence  # [linux]
    - xorg-libxfixes 6.0.1  # [linux]
    - xorg-libxdamage  # [linux]
    - xorg-libxxf86vm  # [linux]
    - libglvnd  # [linux]
    - libunwind 1.5.0  # [linux]

test:
  requires:
    - pkg-config
  commands:
    # Assert that we did NOT build screen rendering capabilities (GLX, EGL, classic libGL)
    # This matches conda-forge and glvnd-based OpenGL usage
    - test ! -f $PREFIX/lib/dri/kms_swrast_dri${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/dri/swrast_dri${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/libgbm${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/libGLESv1_CM${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/libGLESv2${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/libEGL${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/libGL${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libvulkan_lvp${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/share/vulkan/icd.d/lvp_icd.x86_64.json  # [x86_64]
    - test -f $PREFIX/share/vulkan/icd.d/lvp_icd.aarch64.json  # [aarch64]
    - test -f $PREFIX/share/vulkan/icd.d/lvp_icd.ppc64le.json  # [ppc64le]
    - test ! -f $PREFIX/lib/libGLESv1_CM.1${SHLIB_EXT}  # [osx]
    - test ! -f $PREFIX/lib/libGLESv2.2${SHLIB_EXT}  # [osx]
    - test ! -f $PREFIX/lib/libGL.1${SHLIB_EXT}  # [osx]

about:
  home: https://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: docs/license.rst
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.
  description: |
    Mesa is a collection of graphics libraries and drivers that implement a variety of APIs such as OpenGL, Vulkan, and others. It provides software rendering and hardware acceleration for 3D graphics.
  dev_url: https://gitlab.freedesktop.org/mesa/mesa
  doc_url: https://docs.mesa3d.org/

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - sankhesh
    - danlipsa
    - hmaarrfk
    - downiec
    - jasonb5
    - matthiasdiener

# ---
# Notes and Explanations:
#
# - This recipe was previously split into multiple outputs (mesa-libgbm, mesa-libgl, mesa-libegl, etc.) to match CDT and downstream package expectations.
# - After review, we reverted to a single-output package for simplicity, maintainability, and compatibility with conda-forge and upstream practices.
# - glvnd (OpenGL Vendor Neutral Dispatch) is used for OpenGL dispatching, as recommended by conda-forge and upstream.
# - All relevant dependencies and test logic from subpackages have been merged here.
# - Platform selectors are used to ensure only valid libraries are built and tested on each OS.
# - For valid Meson options, see: https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/meson_options.txt
#   - Examples: -Dgallium-drivers=softpipe,llvmpipe,zink, -Dglx=dri, -Degl=enabled/disabled, -Dplatforms=x11,macos, -Dvulkan-drivers=swrast,virtio
# - We explicitly disable or enable features per platform to match upstream and downstream needs.
