{% set version = "25.1.0" %}

package:
  name: mesalib-split
  version: {{ version }}

source:
  url: https://archive.mesa3d.org/mesa-{{ version }}.tar.xz
  sha256: b1c45888969ee5df997e2542654f735ab1b772924b442f3016d2293414c99c14

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - meson
    - pyyaml
    - mako
    - packaging
    - python 3.12  # [linux]
    - flex
    - bison
    - pkg-config
    - llvm
    - llvmdev  # [build_platform != target_platform]
    - glslang
    - git  # [linux]
  host:
    - expat 2.5.0
    - zlib {{ zlib }}
    - zstd {{ zstd }}
    - libdrm  # [linux]
    - spirv-tools 2025.1
    - llvm 17.0.6
    - llvmdev 17.0.6
    - libxcb
    - xorg-libx11
    - xorg-xorgproto
    - xorg-libxrandr
    - xorg-libxshmfence
    - xorg-libxfixes 6.0.1
    - libglvnd-devel  # [linux]
    - libunwind 1.5.0  # [linux]

outputs:
  # Mesa GBM implementation
  - name: mesa-libgbm
    build:
      run_exports:
        - {{ pin_subpackage('mesa-libgbm', max_pin='x.x') }}
      ignore_run_exports:
        - libstdcxx-ng
    files:
      - lib/libgbm.so*
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - libdrm  # [linux]
        - expat
      run:
        - libdrm  # [linux]
        - expat
    test:
      commands:
        - test -f $PREFIX/lib/libgbm${SHLIB_EXT}  # [linux]

  # Base package with core Mesa components
  - name: mesalib
    build:
      run_exports:
        - {{ pin_subpackage('mesalib', max_pin='x.x') }}
      ignore_run_exports:
        - libstdcxx-ng
        - xorg-libx11
        - xorg-libxext
        - llvm
        - llvmdev
    files:
      - lib/dri/*.so*
      - lib/libgallium*.so*
      - include/**.h
      - share/drirc.d/**
      - share/glvnd/**
      - share/mesa/**
      - bin/mesa*
      # Exclude files that belong to specific components
      - exclude lib/*GL*.so*
      - exclude lib/*EGL*.so*
      - exclude lib/libgbm.so*
      - exclude lib/libvulkan_*.so*
      - exclude include/GL/**
      - exclude include/EGL/**
      - exclude include/gbm.h
      - exclude share/vulkan/**
      - exclude lib/pkgconfig/**
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('mesa-libgbm', exact=True) }}  # Needed at build time for linking
        - libdrm  # [linux]
        - xorg-libx11
        - xorg-libxext
        - expat
        - libxcb
        - llvm 17.0.6
        - llvmdev 17.0.6
        - zlib
        - zstd
        - spirv-tools 2025.1
        - xorg-libxshmfence
        - libstdcxx-ng  # [linux]
      run:
        - {{ pin_subpackage('mesa-libgbm', exact=True) }}  # DRI drivers need libgbm.so
        - libdrm  # [linux]
        - xorg-libx11
        - xorg-libxext
        - expat
        - libxcb
        - llvm 17.0.6
        - llvmdev 17.0.6
        - zlib
        - zstd
        - spirv-tools 2025.1
        - xorg-libxshmfence
        - libstdcxx-ng  # [linux]
    test:
      commands:
        - test -f $PREFIX/lib/dri/swrast_dri${SHLIB_EXT}  # [linux]
        - test -f $PREFIX/lib/dri/kms_swrast_dri${SHLIB_EXT}  # [linux]

  # Mesa GL implementation
  - name: mesa-libgl
    build:
      run_exports:
        - {{ pin_subpackage('mesa-libgl', max_pin='x.x') }}
      ignore_run_exports:
        - libstdcxx-ng
        - libglvnd
        - llvm
        - llvmdev
    files:
      - lib/libGLX_mesa.so*
      - lib/libGL.so*
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('mesalib', exact=True) }}
        - libglvnd  # [linux]
        - expat
        - xorg-libx11
        - libxcb
        - libdrm  # [linux]
        - llvmdev 17.0.6
      run:
        - {{ pin_subpackage('mesalib', exact=True) }}
        - libglvnd  # [linux]
        - expat
        - xorg-libx11
        - libxcb
        - libdrm  # [linux]
        - llvmdev 17.0.6
    test:
      commands:
        - test -f $PREFIX/lib/libGLX_mesa${SHLIB_EXT}  # [linux]

  # Mesa GL development files
  - name: mesa-libgl-devel
    build:
      run_exports:
        - {{ pin_subpackage('mesa-libgl', max_pin='x.x') }}
    files:
      - lib/pkgconfig/gl.pc
      - include/GL/*.h
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('mesa-libgl', exact=True) }}
        - libgl-devel  # [linux]
      run:
        - {{ pin_subpackage('mesa-libgl', exact=True) }}
        - libgl-devel  # [linux]
    test:
      requires:
        - pkg-config
      commands:
        - pkg-config --exists gl  # [linux]

  # Mesa EGL implementation
  - name: mesa-libegl
    build:
      run_exports:
        - {{ pin_subpackage('mesa-libegl', max_pin='x.x') }}
      ignore_run_exports:
        - libstdcxx-ng
        - libglvnd
        - mesalib
        - llvm
        - llvmdev
    files:
      - lib/libEGL_mesa.so*
      - lib/libEGL.so*
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('mesalib', exact=True) }}
        - {{ pin_subpackage('mesa-libgbm', exact=True) }}
        - libglvnd  # [linux]
        - libdrm  # [linux]
        - expat
        - xorg-libx11
        - libxcb
        - llvmdev 17.0.6
      run:
        - {{ pin_subpackage('mesalib', exact=True) }}
        - {{ pin_subpackage('mesa-libgbm', exact=True) }}
        - libglvnd  # [linux]
        - libdrm  # [linux]
        - expat
        - xorg-libx11
        - libxcb
        - llvmdev 17.0.6
    test:
      commands:
        - test -f $PREFIX/lib/libEGL_mesa${SHLIB_EXT}  # [linux]

  # Mesa EGL development files
  - name: mesa-libegl-devel
    build:
      run_exports:
        - {{ pin_subpackage('mesa-libegl', max_pin='x.x') }}
    files:
      - lib/pkgconfig/egl.pc
      - include/EGL/*.h
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('mesa-libegl', exact=True) }}
        - libegl-devel  # [linux]
      run:
        - {{ pin_subpackage('mesa-libegl', exact=True) }}
        - libegl-devel  # [linux]
    test:
      requires:
        - pkg-config
      commands:
        - pkg-config --exists egl  # [linux]

  # Mesa GBM development files
  - name: mesa-libgbm-devel
    build:
      run_exports:
        - {{ pin_subpackage('mesa-libgbm', max_pin='x.x') }}
    files:
      - lib/pkgconfig/gbm.pc
      - include/gbm.h
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage('mesa-libgbm', exact=True) }}
      run:
        - {{ pin_subpackage('mesa-libgbm', exact=True) }}
    test:
      requires:
        - pkg-config
      commands:
        - pkg-config --exists gbm  # [linux]

  # Mesa Vulkan drivers
  - name: mesa-vulkan-drivers
    build:
      ignore_run_exports:
        - libstdcxx-ng
        - llvm
        - llvmdev
        - mesalib
    files:
      - lib/libvulkan_*.so*
      - share/vulkan/**
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - glslang
      host:
        - {{ pin_subpackage('mesalib', exact=True) }}
        - expat
        - libdrm  # [linux]
        - xorg-libx11
        - libxcb
        - spirv-tools 2025.1
        - llvmdev 17.0.6
        - zlib
        - zstd
        - xorg-libxshmfence
        - libstdcxx-ng  # [linux]
      run:
        - {{ pin_subpackage('mesalib', exact=True) }}
        - expat
        - libdrm  # [linux]
        - xorg-libx11
        - libxcb
        - spirv-tools 2025.1
        - llvmdev 17.0.6
        - zlib
        - zstd
        - xorg-libxshmfence
        - libstdcxx-ng  # [linux]
    test:
      commands:
        - test -f $PREFIX/lib/libvulkan_swrast${SHLIB_EXT}  # [linux]
        - test -n "$(ls -A $PREFIX/share/vulkan/icd.d/*.json 2>/dev/null)"  # [unix]

about:
  home: https://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: docs/license.rst
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.
  description: |
    Mesa is a collection of graphics libraries and drivers that implement a variety of APIs such as OpenGL, Vulkan, and others. It provides software rendering and hardware acceleration for 3D graphics.
  dev_url: https://gitlab.freedesktop.org/mesa/mesa
  doc_url: https://docs.mesa3d.org/

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - sankhesh
    - danlipsa
    - hmaarrfk
    - downiec
    - jasonb5
    - matthiasdiener