{% set version = "25.1.0" %}

package:
  name: mesalib
  version: {{ version }}

source:
  url: https://archive.mesa3d.org/mesa-{{ version }}.tar.xz
  sha256: b1c45888969ee5df997e2542654f735ab1b772924b442f3016d2293414c99c14

build:
  number: 0
  skip: true  # [win]
  track_features:
    - mesalib
  run_exports:
    - {{ pin_subpackage('mesalib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - meson >=0.63.0
    - ninja
    - pyyaml
    - mako
    - packaging
    - python 3.12
    - flex
    - bison
    - pkg-config
    - glslang
    - git  # [linux]
  host:
    - expat
    - zlib
    - zstd
    - libdrm  # [linux]
    - spirv-tools 2025.1
    - llvmdev 15
    - libxcb  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxshmfence  # [linux]
    - libunwind 1.5.0  # [linux]
  run:
    - expat
    - zlib
    - zstd
    - libdrm  # [linux]
    - spirv-tools
    - libxcb  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxshmfence  # [linux]
test:
  requires:
    - pkg-config
  commands:
    # Assert that we did NOT build screen rendering capabilities (GLX, EGL, classic libGL)
    # This matches conda-forge and glvnd-based OpenGL usage
    - test ! -f $PREFIX/lib/dri/kms_swrast_dri${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/dri/swrast_dri${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/libgbm${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/libGLESv1_CM${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/libGLESv2${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/libEGL${SHLIB_EXT}  # [linux]
    - test ! -f $PREFIX/lib/libGL${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libOSMesa${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libvulkan_lvp${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/share/vulkan/icd.d/lvp_icd.x86_64.json  # [x86_64]
    - test -f $PREFIX/share/vulkan/icd.d/lvp_icd.aarch64.json  # [aarch64]
    - test -f $PREFIX/share/vulkan/icd.d/lvp_icd.ppc64le.json  # [ppc64le]
    - test ! -f $PREFIX/lib/libGLESv1_CM.1${SHLIB_EXT}  # [osx]
    - test ! -f $PREFIX/lib/libGLESv2.2${SHLIB_EXT}  # [osx]
    #- test -f $PREFIX/lib/libOSMesa.8${SHLIB_EXT}     # [osx]
    - test ! -f $PREFIX/lib/libGL.1${SHLIB_EXT}  # [osx]

about:
  home: https://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: docs/license.rst
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.
  description: |
    Mesa is a collection of graphics libraries and drivers that implement a variety of APIs such as OpenGL, Vulkan, and others. It provides software rendering and hardware acceleration for 3D graphics.
  dev_url: https://gitlab.freedesktop.org/mesa/mesa
  doc_url: https://docs.mesa3d.org/

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - sankhesh
    - danlipsa
    - hmaarrfk
    - downiec
    - jasonb5
    - matthiasdiener
