{% set version = "25.1.0" %}

package:
  name: mesalib
  version: {{ version }}

source:
  url: https://archive.mesa3d.org/mesa-{{ version }}.tar.xz
  sha256: b1c45888969ee5df997e2542654f735ab1b772924b442f3016d2293414c99c14

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - meson >=0.63.0
    - ninja
    - pyyaml
    - mako
    - packaging
    - python 3.12
    - flex
    - bison
    - pkg-config
    - llvm
    - llvmdev  # [build_platform != target_platform]
    - glslang
    - git  # [linux]
  host:
    - expat 2.5.0
    - libdrm  # [linux]
    - libgl-devel  # [linux]
    - libglvnd  # [linux]  # glvnd is the OpenGL vendor-neutral dispatch library
    - libglvnd-devel  # [linux]
    - libunwind 1.5.0  # [linux]
    - libxcb  # [linux]
    - llvm 17.0.6
    - llvmdev 17.0.6
    - spirv-tools 2025.1
    - xorg-libx11  # [linux]
    - xorg-libxdamage  # [linux]
    - xorg-libxfixes 6.0.1  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxshmfence  # [linux]
    - xorg-libxxf86vm  # [linux]
    - xorg-xorgproto  # [linux]
    - zlib
    - zstd
  run:
    - expat 2.5.0
    - libdrm  # [linux]
    - libglvnd  # [linux]
    - libunwind 1.5.0  # [linux]
    - libxcb  # [linux]
    - llvm 17.0.6
    - llvmdev 17.0.6
    - spirv-tools 2025.1
    - xorg-libx11  # [linux]
    - xorg-libxdamage  # [linux]
    - xorg-libxfixes 6.0.1  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxshmfence  # [linux]
    - xorg-libxxf86vm  # [linux]
    - xorg-xorgproto  # [linux]
    - zlib
    - zstd

test:
  requires:
    - pkg-config
  commands:
    # Check for core Mesa libraries
    - test -f $PREFIX/lib/libGLX_mesa${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libGL.so*  # [linux]
    - test -f $PREFIX/lib/libgbm${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libEGL_mesa${SHLIB_EXT}  # [linux]
    - test -f $PREFIX/lib/libvulkan_*.so*  # [linux]
    - test -n "$(ls -A $PREFIX/share/vulkan/icd.d/*.json 2>/dev/null)"  # [unix]
    # Check for pkg-config files
    - pkg-config --exists gl  # [linux]
    - pkg-config --exists egl  # [linux]
    - pkg-config --exists gbm  # [linux]
    # macOS: check for expected libraries (Mesa 25.1.0 may not provide all)
    - test ! -f $PREFIX/lib/libGLESv1_CM${SHLIB_EXT}  # [osx]
    - test ! -f $PREFIX/lib/libGLESv2${SHLIB_EXT}  # [osx]
    - test ! -f $PREFIX/lib/libGL.1${SHLIB_EXT}  # [osx]
    # Vulkan ICD JSON files (if present)
    - test -n "$(ls -A $PREFIX/share/vulkan/icd.d/*.json 2>/dev/null)"  # [osx]

about:
  home: https://www.mesa3d.org
  license: MIT
  license_family: MIT
  license_file: docs/license.rst
  summary: Mesa is an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.
  description: |
    Mesa is a collection of graphics libraries and drivers that implement a variety of APIs such as OpenGL, Vulkan, and others. It provides software rendering and hardware acceleration for 3D graphics.
  dev_url: https://gitlab.freedesktop.org/mesa/mesa
  doc_url: https://docs.mesa3d.org/

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - sankhesh
    - danlipsa
    - hmaarrfk
    - downiec
    - jasonb5
    - matthiasdiener

# ---
# Notes and Explanations:
#
# - This recipe was previously split into multiple outputs (mesa-libgbm, mesa-libgl, mesa-libegl, etc.) to match CDT and downstream package expectations.
# - After review, we reverted to a single-output package for simplicity, maintainability, and compatibility with conda-forge and upstream practices.
# - glvnd (OpenGL Vendor Neutral Dispatch) is used for OpenGL dispatching, as recommended by conda-forge and upstream.
# - All relevant dependencies and test logic from subpackages have been merged here.
# - Platform selectors are used to ensure only valid libraries are built and tested on each OS.
# - For valid Meson options, see: https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/meson_options.txt
#   - Examples: -Dgallium-drivers=softpipe,llvmpipe,zink, -Dglx=dri, -Degl=enabled/disabled, -Dplatforms=x11,macos, -Dvulkan-drivers=swrast,virtio
# - We explicitly disable or enable features per platform to match upstream and downstream needs.
