travis:
  secure:
    BINSTAR_TOKEN: urvnAAuudUlqNyds0nunxyBLAOZyj2HPuQyzgMuUC4gG79yy435i0wdpHLiEInWLAWOc2evI+9jwEX+wfde66UCy9ztg6ZmC/diNc+Uyn25VgFTMPR3BqsNb3GscYAjnrhgaemVITQt6WuPQzhhcwnAA7mUpFq288odyEz1pEBNiszUrION0l15nr/ewSk9QBRA1Zt8MAFfWM70Y7t+0YNqnmrNRnfw0kRO1EfQMeNkTCSdaFbmfek89GP0iztF08ozH6qXvpwtpYCdFQqo6GR4a1xrnZ+8H7k2DQ5rwgjyf4UD2rFqmqYtY7CbNph5FIgeAS9scLaXYwzkPo871XiJE81/G/2K4L47Dl7AZqqiF9VE2o4HU9G369arUwfGB6r+ZhOzYhW4yIKGe/xzpUI3dPSW8PuNCc1CgSU9IZSgR5XyvivLU64HcAfzlxt8V2y6FeebMB552cP1S0jNtYVPao3Gy0uoMCyG8ywKatG6aPRS4pvwETeTI2XX6RowP6lKstTNqvE9mFTD4qUHlWrOFwX3B7erMgnznm1s6+9EZvAtot45HpBnSYa89JiWwSwyBqdiItnNPRfsUCvZittj+CfCMRNN5XiDFRVwlJ7Q7bwMcc17H2RdJlOz+dK7OwIQJsZCvVBx7j3yl0bt0lmxBmZZs3oQzMZ6hgV+p9QU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
