travis:
  secure:
    BINSTAR_TOKEN: OX/zLt/NA0KD4fPRo2o284fD6jNLUBhm72FSa0zL2JqkcVRZmArtCa95a6fFHHxE7QUATbh8dpNM9HcEywWVM2+VSCHeMuAZOzM7I4PYYUCWjP3H+/FddnELL0c1w309wBWJGSix1z+osKq8t9K67A9lLhLxmoTjIA0rq/iflC7VxPCLwRu1UIwzkN6x6qZzIjIS0Sb/bhUmY33vcDCIfriaS9Ohht3PBDzDlwdCqGJpcb1lD5m8tzziO+C0Vzhao9RA+OqcQwVe7IdD+z5BVIX0dyuxJ/Uw/FCSvkACEhAMuzeLXkXuoFj830eLwcqwFxsfVNwTLnlJI3nndomri3YLvKV+qIiHlckRIELkk0Oap89Eqb8lSfYIoNJ0UxelJEWaIzpWNLRmVvks/CSZHkR7OaRPuDExpN8dOtoWSx/6C+dTpQ0AFXm1/heyaFD4+11Zv6v/wxKbrZ6PGWMCspuoLLvObnkNklBzPULhDjoFumwXhf5gX8/qWADZmm+x8iFBQVVt2Nz8AHY+NSwG4EExrmPzj6yc3trynsJOBF4hVKFRz60IGixAilntJ8Um8aUayVyHqO8Q4Vndjd2HAQsCSS/u8suQsmYVcDYNNwFswPuxfxg35ewkkrUn2ceFsco2UPvVz307mqWDcvT/JfgpaQK7EIDeB75hQjF9Fgk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
